---
- hosts: installserver
  user: root
  tasks:
  - name: Configure proper network
    hostname: name=installserver
  - name: Install private keys
    copy: src=ssh/id_rsa
          dest=/root/.ssh/id_rsa
          mode=600
  - name: Install public keys
    copy: src=ssh/id_rsa.pub
          dest=/root/.ssh/id_rsa.pub
  - name: Add authorized_keys
    authorized_key: user=root
                    key="{{ item }}"
    with_file:
      - ssh/id_rsa.pub


- hosts: openstack1
  user: root
  tasks:
  - name: Configure proper network
    hostname: name=openstack1
  - name: Add authorized_keys
    authorized_key: user=root
                    key="{{ item }}"
    with_file:
      - ssh/id_rsa.pub

- hosts: openstack2
  user: root
  tasks:
  - name: Configure proper network
    hostname: name=openstack2
  - name: Add authorized_keys
    authorized_key: user=root
                    key="{{ item }}"
    with_file:
      - ssh/id_rsa.pub

- hosts: openstack3
  user: root
  tasks:
  - name: Configure proper network
    hostname: name=openstack3
  - name: Add authorized_keys
    authorized_key: user=root
                    key="{{ item }}"
    with_file:
      - ssh/id_rsa.pub
