---
- hosts: localhost
  tasks:
    - local_action: template src=ssh.config.tmpl dest=./ssh.config
- hosts: hypervisor
  roles:
    - hypervisor

- hosts: openstack-nodes
  user: root
  roles:
    - openstack-node

- hosts: install-server
  user: root
  roles:
    - install-server
