---
- name: Copy network configuration on the host
  copy: src=spinalstack.xml
        dest=/tmp/spinalstack.xml

- name: Configure the network
  command: virsh net-create /tmp/spinalstack.xml
  sudo: True

- name: Configure the different domains
  virt: name={{ item }}
        command=define
        uri=qemu:///system
        xml="{{ lookup('file',  item + '.xml') }}"
  with_items: nodes
  sudo: True
  
- name: Start the domains
  virt: name={{ item }}
        state=running
        uri=qemu:///system
  with_items: nodes

- name: Copy XML device snippet
  copy: src=libvirt/{{ item }}.xml
        dest=/tmp
  with_items:
    - openstack1-ceph41
    - openstack1-ceph42
    - openstack1-ceph43
    - openstack1-ceph44
    - openstack2-ceph41
    - openstack2-ceph42
    - openstack2-ceph43
    - openstack2-ceph44
    - openstack3-ceph41
    - openstack3-ceph42
    - openstack3-ceph43
    - openstack3-ceph44

- name: Load the disks openstack1
  command: virsh attach-device openstack1 /tmp/{{ item }}.xml
  with_items:
    - openstack1-ceph41
    - openstack1-ceph42
    - openstack1-ceph43
    - openstack1-ceph44
  sudo: True

- name: Load the disks openstack2
  command: virsh attach-device openstack2 /tmp/{{ item }}.xml
  with_items:
    - openstack2-ceph41
    - openstack2-ceph42
    - openstack2-ceph43
    - openstack2-ceph44
  sudo: True

- name: Load the disks openstack3
  command: virsh attach-device openstack3 /tmp/{{ item }}.xml
  with_items:
    - openstack3-ceph41
    - openstack3-ceph42
    - openstack3-ceph43
    - openstack3-ceph44
  sudo: True

- name: Wait for server to restart
  # IP are hard coded because we cannot lookup the IP from the hosts file
  # using a with_items look.
  local_action: wait_for host={{ item }} port=22 timeout=600
  with_items:
    - 192.168.142.5
    - 192.168.142.6
    - 192.168.142.7
    - 192.168.142.8
