---
- name: Copy network configuration on the host
  copy: src=spinalstack.xml
        dest=/tmp/spinalstack.xml

- name: Configure the network
  command: virsh net-create /tmp/spinalstack.xml

- name: Configure the different domains
  virt: name={{ item }}
        command=define
        uri=qemu:///system
        xml="{{ lookup('file',  item + '.xml') }}"
  with_items: nodes
  
- name: Start the domains
  virt: name={{ item }}
        state=running
        uri=qemu:///system
  with_items: nodes

- name: Wait for server to restart
  local_action:
    module: wait_for
     host={{ item }}
     port=22
     delay=1
     timeout=3000
  with_items: nodes
