---
- name: Configure proper network
  hostname: name={{ ansible_hostname }}

- name: Install private keys
  copy: src=ssh/id_rsa
        dest=/root/.ssh/id_rsa
        mode=600

- name: Install public keys
  copy: src=ssh/id_rsa.pub
        dest=/root/.ssh/id_rsa.pub

- name: Add authorized_keys
  authorized_key: user=root
                  key="{{ item }}"
  with_file:
    - ssh/id_rsa.pub

- name: Remove rhel-source
  file: path=/etc/yum.repos.d/rhel-source.repo state=absent

- name: create hosts file
  copy: src=hosts
        dest=/etc/hosts

- name: Retrieve the Puppetfile
  git:  repo="{{ puppetfile.repo }}"
        dest=/tmp/puppetfile
        version="{{ puppetfile.commit }}"
  with_dict: puppetfile

- name: Retrieve puppet-openstack-cloud module
  git:  repo="{{ module.repo }}"
        dest=/tmp/puppet-openstack-cloud
        version="{{ module.commit }}"
  with_dict: module

- name: Retrieve openstack-yaml-infra
  git:  repo="{{ infrastructure.repo }}"
        dest=/tmp/openstack-yaml-infra
        version="{{ infrastructure.commit }}"
  with_dict: infrastructure

- name: Retrieve serverspec
  git:  repo="{{ serverspec.repo }}"
        dest=/tmp/openstack-serverspec
        version="{{ serverspec.commit }}"
  with_dict: serverspec

- name: Retrieve config-tools
  git:  repo="{{ configtools.repo }}"
        dest=/tmp/config-tools
        version="{{ configtools.commit }}"
  with_dict: configtools

- name: Retrieve jenkins jobs
  git:  repo="{{ jenkins.repo }}"
        dest=/etc/jenkins_jobs
        version="{{ jenkins.commit }}"
  with_dict: jenkins

- name: Retrieve env
  git:  repo="{{ env.repo }}"
        dest=/tmp/spinalstack-env
        version="{{ env.commit }}"
  with_dict: env

- name: Ensure Jenkins is sudoer with no password
  lineinfile: dest=/etc/sudoers.d/jenkins create=yes line="jenkins ALL=(ALL) NOPASSWD:ALL"

- name: Install autojenkins pip
  pip: name=autojenkins

# Scipts
- name: Copy the scripts file
  command: cp /tmp/config-tools/{{ item }} /usr/bin/
  with_items:
    - configure.sh
    - verify-servers.sh
    - generate.py
    - extract.py
    - merge.py
    - health-check.sh

- name: Copy the Tempst files
  command: cp -r /tmp/config-tools/tempest /opt/tempest-scripts

- name: Create necessary folder
  command: mkdir -p {{ item }}
  with_items:
    - /etc/config-tools

- name: Copy the config.tmpl file
  command: cp /tmp/config-tools/{{ item }} /etc/config-tools/
  with_items:
    - config.tmpl

- name: Copy the openrc file
  copy: src=openrc.sh
        dest=/etc/config-tools/openrc.sh
        mode=0755

- name: Create the jenkins jobs
  shell: jenkins-jobs update --delete-old /etc/jenkins_jobs/jobs

- name: Create necessary folder
  command: bash -c "merge.py /tmp/openstack-yaml-infra/scenarios/3nodes/infra.yaml /tmp/spinalstack-env/3nodes.yaml > /etc/config-tools/global.yml"

- name: Create necessary folder
  command: bash -c "generate.py 0 /etc/config-tools/global.yml /tmp/config-tools/config.tmpl > /etc/config-tools/config"

# ServerSpec
- name: Create the serverspec files
  command: cp -r /tmp/openstack-serverspec/ /etc/serverspec

- name: Create the serverspec arch.yml.tpml file
  command: cp /tmp/openstack-yaml-infra/arch.yml.tmpl /etc/serverspec/

# Puppet
- name: Create puppet necessary folders
  command: mkdir -p /etc/puppet/{{ item }}
  with_items:
    - manifests
    - data
    - modules

- name: put the configuration files on the right place
  command: cp /tmp/openstack-yaml-infra/data/{{ item }} /etc/puppet/data/{{ item }}
  with_items:
    - common.yaml.tmpl
    - fqdn.yaml.tmpl
    - type.yaml.tmpl

- name: Get the module from the Puppetfile
  command: r10k --verbose 3 puppetfile install
  environment:
    PUPPETFILE: /tmp/puppetfile/Puppetfile
    PUPPETFILE_DIR: /etc/puppet/modules

- name: Create the site.pp
  copy: content="Exec {\n
   path => '/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin'\n
   }\n
   hiera_include('classes')\n
   "
    dest=/etc/puppet/manifests/site.pp

- name: Enable launch-job script
  copy: src=launch-job.py
        dest=/bin/launch-job.py
        mode=0755

- name: Launch CI jobs
  shell: launch-job.py http://installserver.example.com:8282/ puppet
